### ISSUE TITLE
https://kobito.qiita.com/ で証明書エラーが出る

### ISSUE THREAD

**Issue by yoshiken** [increments/kobito.qiita.com#36]
# What / どんな問題か

タイトル通り
# REPRO STEPS / 再現環境

OS/Browser: Mac/Google Chrome
本番環境
# EXPECTED BEHAIVOR / 期待される動作

証明書が正しく配置されアクセス時に警告が出ない

**Comment by r7kamura** [comment]
背景として次のような都合がある。

- GitHub Pagesで実現しているのでSSLに対応しにくい
- CloudFlareを間に入れるとSSL対応できるがサブドメインで運用している都合やりにくい

問題なのは「アクセスするとエラーが出る」というところで「通信が暗号化されていない」というのが問題なわけではないと思うので、必ずしも「証明書が正しく配置されアクセス時に警告が出ない」という状態にするのが取るべき行動ではないと思う。

簡単な解決策として、例えばhttpsでアクセスしたときにhttpにリダイレクトする、というようなコードをJavaScriptで入れるだけでも解決されるかもしれない。

**Comment by uasi** [comment]
その JavaScript をロードする index.html は HTTPS でアクセスされるからそこで警告がでると思う

**Comment by r7kamura** [comment]
@uasi どう対処すべき？

**Comment by iogi** [comment]
https://kobito.qiita.com/ HTTPS化した
